import axios from 'axios';
import React, { Component } from 'react';

export default function Api() {
    const api = axios.create({
        baseURL: 'https://api.github.com',
    });

    const apiGaleria = [
        // require('./../assets/gallery/avatar(1).jpg'),
        // require('./../assets/gallery/avatar(2).jpg'),
        // require('./../assets/gallery/avatar(3).jpg'),
        // require('./../assets/gallery/avatar(4).jpg'),
        // require('./../assets/gallery/avatar(5).jpg'),
        // require('./../assets/gallery/avatar(6).jpg'),
        // require('./../assets/gallery/avatar(7).jpg'),
        // require('./../assets/gallery/avatar(8).jpg'),
        // require('./../assets/gallery/avatar(9).jpg'),
        // require('./../assets/gallery/avatar(10).jpg'),
        // require('./../assets/gallery/avatar(11).jpg'),
        // require('./../assets/gallery/avatar(12).jpg'),
        // require('./../assets/gallery/avatar(13).jpg'),
        // require('./../assets/gallery/avatar(4).jpg'),
        // require('./../assets/gallery/avatar(6).jpg'),
        // require('./../assets/gallery/avatar(7).jpg'),
        // require('./../assets/gallery/avatar(8).jpg'),
        // require('./../assets/gallery/avatar(9).jpg'),
        // require('./../assets/gallery/avatar(10).jpg'),
        // require('./../assets/gallery/avatar(11).jpg'),
        // require('./../assets/gallery/avatar(12).jpg'),
        // require('./../assets/gallery/avatar(13).jpg'),
        // require('./../assets/gallery/avatar(4).jpg'),
        // require('./../assets/gallery/avatar(9).jpg'),
        // require('./../assets/gallery/avatar(10).jpg'),
        // require('./../assets/gallery/avatar(11).jpg'),
        // require('./../assets/gallery/avatar(12).jpg'),
        // require('./../assets/gallery/avatar(13).jpg'),
        // require('./../assets/gallery/avatar(4).jpg'),
        // require('./../assets/gallery/avatar(6).jpg'),
        // require('./../assets/gallery/avatar(7).jpg'),
        // require('./../assets/gallery/avatar(8).jpg'),
        // require('./../assets/gallery/avatar(9).jpg'),
        // require('./../assets/gallery/avatar(10).jpg'),
        // require('./../assets/gallery/avatar(11).jpg'),
        // require('./../assets/gallery/avatar(12).jpg'),
        // require('./../assets/gallery/avatar(13).jpg'),
        // require('./../assets/gallery/avatar(4).jpg'),
        require('./../assets/gallery/av(1).jpg'),
        require('./../assets/gallery/av(2).jpg'),
        require('./../assets/gallery/av(3).jpg'),
        require('./../assets/gallery/av(4).jpg'),
        require('./../assets/gallery/av(5).jpg'),
        require('./../assets/gallery/av(6).jpg'),
        require('./../assets/gallery/av(7).jpg'),
        require('./../assets/gallery/av(8).jpg'),
        require('./../assets/gallery/av(9).jpg'),
        require('./../assets/gallery/av(10).jpg'),
        require('./../assets/gallery/av(11).jpg'),
        require('./../assets/gallery/av(12).jpg'),
        require('./../assets/gallery/av(13).jpg'),
        require('./../assets/gallery/av(14).jpg'),
        require('./../assets/gallery/av(15).jpg'),
        require('./../assets/gallery/av(16).jpg'),
        require('./../assets/gallery/av(17).jpg'),
        require('./../assets/gallery/av(18).jpg'),
        require('./../assets/gallery/av(19).jpg'),
        require('./../assets/gallery/av(20).jpg'),
        require('./../assets/gallery/av(21).jpg'),
        require('./../assets/gallery/av(22).jpg'),
        require('./../assets/gallery/av(23).jpg'),
        require('./../assets/gallery/av(24).jpg'),
        require('./../assets/gallery/av(25).jpg'),
        require('./../assets/gallery/av(26).jpg'),
        require('./../assets/gallery/av(27).jpg'),
        require('./../assets/gallery/av(28).jpg'),
        require('./../assets/gallery/av(29).jpg'),
        require('./../assets/gallery/av(30).jpg'),
        require('./../assets/gallery/av(31).jpg'),
        require('./../assets/gallery/av(32).jpg'),
        require('./../assets/gallery/av(33).jpg'),
        require('./../assets/gallery/av(34).jpg'),
        require('./../assets/gallery/av(35).jpg'),
        require('./../assets/gallery/av(36).jpg'),
        require('./../assets/gallery/av(37).jpg'),
        require('./../assets/gallery/av(38).jpg'),
        require('./../assets/gallery/av(39).jpg'),
        require('./../assets/gallery/av(40).jpg'),
        require('./../assets/gallery/av(41).jpg'),
        require('./../assets/gallery/av(42).jpg'),
        require('./../assets/gallery/av(43).jpg'),
        require('./../assets/gallery/av(44).jpg'),
        require('./../assets/gallery/av(45).jpg'),
        require('./../assets/gallery/av(46).jpg'),
        require('./../assets/gallery/av(47).jpg'),
        require('./../assets/gallery/av(48).jpg'),
    ];
    return { Api, apiGaleria };
}
